apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::361588996336:instance-profile/ruben-eks-EKSClusterInstanceProfile-1HPFVIGZ1PQ1
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::825317146186:role/amanda
      username: amanda
      groups:
        - system:masters
